# Generated by Django 2.1 on 2020-07-21 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(null=True)),
                ('duration', models.IntegerField()),
                ('negative', models.BooleanField()),
                ('creator', models.CharField(max_length=500)),
                ('organisation', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
