# Generated by Django 2.1 on 2020-07-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_maker', '0002_createtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=5000)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_maker.CreateTest')),
            ],
        ),
    ]
