# Generated by Django 3.0.7 on 2020-07-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionBank', models.TextField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('typee', models.CharField(max_length=200)),
                ('dur', models.CharField(max_length=200)),
            ],
        ),
    ]
