# Generated by Django 3.0.7 on 2020-07-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QQ_1', models.TextField(max_length=200, unique=True)),
                ('op_1', models.TextField(max_length=200, unique=True)),
                ('op_2', models.TextField(max_length=200, unique=True)),
                ('op_3', models.TextField(max_length=200, unique=True)),
            ],
        ),
    ]
