# Generated by Django 3.0.7 on 2020-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.TextField(max_length=200, unique=True)),
                ('a1', models.TextField(max_length=200, unique=True)),
                ('b1', models.TextField(max_length=200, unique=True)),
                ('c1', models.TextField(max_length=200, unique=True)),
                ('d1', models.TextField(max_length=200, unique=True)),
            ],
        ),
    ]
