# Generated by Django 3.0.7 on 2020-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_multp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q2', models.TextField(max_length=200, unique=True)),
                ('es', models.TextField(max_length=200, unique=True)),
            ],
        ),
    ]
