# Generated by Django 2.1.3 on 2020-06-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20200623_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organisation',
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
