# Generated by Django 2.1 on 2020-07-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManyCorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_type', models.CharField(blank=True, default='ManyCorrect', max_length=1000, null=True)),
                ('ques', models.CharField(max_length=2000)),
                ('op_a', models.CharField(max_length=1000)),
                ('op_b', models.CharField(max_length=1000)),
                ('op_c', models.CharField(max_length=1000)),
                ('op_d', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('marks', models.IntegerField(blank=True, default=10, null=True)),
                ('negative_marks', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_type', models.CharField(blank=True, default='MCQ', max_length=1000, null=True)),
                ('ques', models.CharField(max_length=2000)),
                ('op_a', models.CharField(max_length=1000)),
                ('op_b', models.CharField(max_length=1000)),
                ('op_c', models.CharField(max_length=1000)),
                ('op_d', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('marks', models.IntegerField(blank=True, default=10, null=True)),
                ('negative_marks', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_type', models.CharField(blank=True, default='OpenAnswer', max_length=1000, null=True)),
                ('ques', models.CharField(max_length=2000)),
                ('answer', models.TextField(max_length=50000)),
                ('marks', models.IntegerField(blank=True, default=10, null=True)),
                ('negative_marks', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('category', models.CharField(max_length=1000)),
                ('exam_type', models.CharField(max_length=1000)),
                ('visibility', models.CharField(max_length=1000)),
                ('creator', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('category', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('duration', models.IntegerField()),
                ('negative', models.BooleanField()),
                ('creator', models.CharField(max_length=500)),
                ('organisation', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='openanswer',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_admin.Questionbank'),
        ),
        migrations.AddField(
            model_name='openanswer',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_admin.Test'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_admin.Questionbank'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_admin.Test'),
        ),
        migrations.AddField(
            model_name='manycorrect',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_admin.Questionbank'),
        ),
        migrations.AddField(
            model_name='manycorrect',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_admin.Test'),
        ),
    ]
